### ISSUE TITLE
Fix corruption of db file

### ISSUE THREAD

**Issue by BugOrFeature** [ProgrammingLife2017/DynamiteAndButterflies#83]
The database gets corrupted upon incorrectly closing the program.

**Comment by LBoleij** [comment]
Responsible: Lex
Hours: 2
Priority: A

**Comment by LBoleij** [comment]
Real time: 15 hours. It seemed impossible to release the db file after the error had occurred, so it was impossible to remove the files, this took a lot of research to fix, hence the extra hours
