### ISSUE TITLE
QOL - Recently used files

### ISSUE THREAD

**Issue by BugOrFeature** [ProgrammingLife2017/DynamiteAndButterflies#85]
Be able to use recently used files to enhance the user experience.

**Comment by LBoleij** [comment]
Responsible: Jip
Hours: 2
Priority: B

**Comment by Jipje** [comment]
Is working out pretty well. Still a bug.
Load a file -> Load different file -> Load first file gives exception. After that is fixed we can open PR.

Already written some user stories on the drive.https://docs.google.com/document/d/1l-3cPMOefGl3E1t-KoQgqietoI4yLZQjFRDazKFhQnY/edit#
